// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// combi2inds
Rcpp::DataFrame combi2inds(const Rcpp::CharacterVector inputVector);
RcppExport SEXP _STK_combi2inds(SEXP inputVectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector >::type inputVector(inputVectorSEXP);
    rcpp_result_gen = Rcpp::wrap(combi2inds(inputVector));
    return rcpp_result_gen;
END_RCPP
}
// crossatan
NumericMatrix crossatan(NumericMatrix m1, NumericMatrix m2);
RcppExport SEXP _STK_crossatan(SEXP m1SEXP, SEXP m2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m2(m2SEXP);
    rcpp_result_gen = Rcpp::wrap(crossatan(m1, m2));
    return rcpp_result_gen;
END_RCPP
}
// crossdist
NumericMatrix crossdist(NumericMatrix m1, NumericMatrix m2);
RcppExport SEXP _STK_crossdist(SEXP m1SEXP, SEXP m2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m2(m2SEXP);
    rcpp_result_gen = Rcpp::wrap(crossdist(m1, m2));
    return rcpp_result_gen;
END_RCPP
}
// eigenMapMatMult2
SEXP eigenMapMatMult2(const Eigen::Map<Eigen::MatrixXd> A, Eigen::Map<Eigen::MatrixXd> B, int n_cores);
RcppExport SEXP _STK_eigenMapMatMult2(SEXP ASEXP, SEXP BSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenMapMatMult2(A, B, n_cores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_STK_combi2inds", (DL_FUNC) &_STK_combi2inds, 1},
    {"_STK_crossatan", (DL_FUNC) &_STK_crossatan, 2},
    {"_STK_crossdist", (DL_FUNC) &_STK_crossdist, 2},
    {"_STK_eigenMapMatMult2", (DL_FUNC) &_STK_eigenMapMatMult2, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_STK(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
