# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

combi2inds <- function(inputVector) {
    .Call(`_STK_combi2inds`, inputVector)
}

crossatan <- function(m1, m2) {
    .Call(`_STK_crossatan`, m1, m2)
}

crossdist <- function(m1, m2) {
    .Call(`_STK_crossdist`, m1, m2)
}

eigenMapMatMult2 <- function(A, B, n_cores) {
    .Call(`_STK_eigenMapMatMult2`, A, B, n_cores)
}

